### ISSUE TITLE
If users home directory does not exist, fails to create necessary directory structure and errors out.

### ISSUE THREAD

**Issue by zarry** [nickola/chef-ssh-keys#6]
If users home directory does not exist, recipe fails to create necessary directory structure and errors out.

I ran into an issue where a users home directory was manually removed.  This failed the chef run as the needed directory structure was not present.  This presented itself as an issue because of this currently open chef bug. [CHEF-2409](https://tickets.opscode.com/browse/CHEF-2409)

Adding recursive true to the directory call will solve this issue and prevent a chef run from failing.

**Comment by nickola** [comment]
Merged. Thank you!

**Comment by logankoester** [comment]
Thanks for getting around to this @nickola, much appreciated!
