### ISSUE TITLE
Error when doing  knife cookbook site install ssh-keys

### ISSUE THREAD

**Issue by psychonaut** [nickola/chef-ssh-keys#8]
eloy@dellta:/srv/repo/chlor-chef-repo$ knife cookbook site install ssh-keys
Installing ssh-keys to /srv/repo/chlor-chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-ssh-keys) exists, switching to it.
Downloading ssh-keys from the cookbooks site at version 1.0.0 to /srv/repo/chlor-chef-repo/cookbooks/ssh-keys.tar.gz
Cookbook saved: /srv/repo/chlor-chef-repo/cookbooks/ssh-keys.tar.gz
Removing pre-existing version.
Uncompressing ssh-keys version 1.0.0.
removing downloaded tarball
1 files updated, committing changes
ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git add ssh-keys ----
STDOUT: 
STDERR: fatal: Not a git repository: /Users/Nickola/Development/.chef/.git/modules/site-cookbooks/ssh-keys
---- End output of git add ssh-keys ----
Ran git add ssh-keys returned 128

**Comment by nickola** [comment]
Fixed.
See latest version on Chef Supermarket: https://supermarket.chef.io/cookbooks/ssh-keys
